apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: {{ .Values.namespace }}
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: SbConnStr
        key: SbConnStr
auth:
  secretStore: secretstore
scopes:
  - tenantservice
  - userservice
