apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: {{ .Values.namespace }}
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: {{ .Values.kvName }}.vault.azure.net
    - name: spnTenantId
      value: {{ .Values.tenantId }}
    - name: spnClientId
      value: {{ .Values.aksIdentityClientId }}
