apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenantservice
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: tenantservice.{{ .Values.aksHttpAppRoutingZoneName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tenantservice
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tenantservice
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tenantservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenantservice
  namespace: {{ .Values.namespace }}
  labels:
    app: tenantservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenantservice
  template:
    metadata:
      labels:
        app: tenantservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tenantservice"
        dapr.io/app-port: "5000"
        dapr.io/sidecar-liveness-probe-delay-seconds: "10"
    spec:
      containers:
        - name: tenantservice
          image: {{ .Values.tenantServiceContainerImage }}
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
