apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      # When using Docker Compose for local development, the volume '/dapr/components/' is mapped to '/components'.
      value: /components/secrets.json
    - name: nestedSeparator
      value: "."
